### ISSUE TITLE
warning: pcm_readi buffer overrun

### ISSUE THREAD

**Issue by Ra0EL** [Arkq/svar#1]
Hi,
I am giving a try to `svar`, as it seems more convenient and accurate than my scripts using `sox`.  
And indeed, it works fine.  

But, is there a way to avoid resource conflict, when I am trying to use `svar` in parallel with `motion` ?
I don't have any problem to use `motion` and `sox` in parallel in order to capture both video and sound records.
When I try the same with `svar` , the following message scrolls infinitely in terminal : 

```
warning: pcm_readi buffer overrun
```

And yes, I am using the same and only one webcam USB-connected to my machine, for all these commands.  

Thank you for suggestions.

**Comment by Arkq** [comment]
Hi,

On what machine (CPU power) you are running this? Because it seems, that the `svar` is not running fast enough - the thread responsible for reading data is too slow. Also what output format you are using (if you are using OGG, switch to WAV)? And finally, how you are running `svar` (command line options)?

**Comment by Ra0EL** [comment]
For my system :
```
System:    Kernel: 4.13.12-1-default x86_64 bits: 64 Desktop: KDE Plasma 5.11.3
           Distro: openSUSE Tumbleweed 20171117
Machine:   Device: desktop System: Dell product: Precision WorkStation T5500 serial: N/A
           Mobo: Dell model: 0CRH6C v: A02 serial: N/A BIOS: Dell v: A09 date: 04/20/2011
CPU(s):    2 Quad core Intel Xeon E5620s (-HT-MCP-SMP-) speed/max: 1992/2313 MHz
Graphics:  Card: NVIDIA GF106GL [Quadro 2000]
           Display Server: x11 (X.org 1.19.5 ) drivers: nouveau (unloaded: modesetting,fbdev,nv,vesa)
Network:   Card-1: Broadcom Limited NetXtreme BCM5761 Gigabit Ethernet PCIe driver: tg3
           Card-2: 3Com 3c905B 100BaseTX [Cyclone] driver: 3c59x
Drives:    HDD Total Size: 5007.0GB (19.7% used)
Info:      Processes: 482 Uptime: 4 days  6:36 Memory: 10208.7/11996.5MB Init: systemd runlevel: 5 
```

As for svar, I mostly stick to default : 
```
svar -D hw:2,0 -l 5
```

**Comment by Arkq** [comment]
OK, so you are running it on decent PC. The CPU is definitely not a problem then - at lest it shouldn't be. I thought, that you are running this on some ARM-based micro-board.

However, you might try to use something different than hw:2,0. Maybe there is a "default" PCM for this card (try `arecord -L`). Using "hw" PCM is advised only when one wants to use audio device with a minimal possible delay or does not want to waste CPU resources (it might omit some ALSA audio processing).

And one more question. Does `svar` produce any audio output? or maybe it simply prints "pcm_readi buffer overrun" warning message without any audio? Because, if there is no audio output at all, it might suggest, that the audio device is locked by some other application.

Anyway, I'll try to investigate this further.

**Comment by Arkq** [comment]
I've freshened up the codebase a little bit. However, the logic is (mostly) unchanged. Anyway, please compile current master branch with the `--enable-debug` configuration flag, as follows:

    ../configure --enable-vorbis --enable-sndfile --enable-debug

Then, run `svar` with the `-v` flag and past the output here (everything before first `pcm_readi buffer overrun` warning).

**Comment by Arkq** [comment]
This issue seems to be stale, I'm closing it. If the bug still remains, please reopen with some more info.
