### ISSUE TITLE
does not split files

### ISSUE THREAD

**Issue by tr4bl3** [Arkq/svar#5]
does not split files in all formats

**Comment by Arkq** [comment]
Could you be more specific? What format, when splitting does not work? Please, post svar command line invocation.

**Comment by tr4bl3** [comment]
i try in WAV and other format (mp3, ogg)
command line:
svar --verbose --sig-level=0 --split-time=30 --sig-meter
svar -s 10 -o MP3
svar --split-time=30
svar --sig-level=0 --split-time=30
svar -v -l 0 -s 30
but it does not split files
maybe I'm doing something wrong?

**Comment by Arkq** [comment]
> svar --sig-level=0 --split-time=30

This will not split, because volume will be never below 0. New file is created if incoming signal is **below** signal level for more than the split-time, e.g.:

```
$ svar -s 10 -o mp3 -v
SVAR - Simple Voice Activated Recorder
Selected PCM device: default
Hardware parameters: 44100 Hz, S16LE, 1 channel
Output file format: mp3
Output bit rate [min, max]: 32, 128 kbit/s
info: Creating new output file: rec-06-21:34:28.mp3
info: Creating new output file: rec-06-21:35:00.mp3
info: Creating new output file: rec-06-21:35:22.mp3
```

Use `--sig-level=1`. If you need better signal sensitivity, I think that it will be required to allow fractional values for signal level (code change), or boost microphone gain.

**Comment by tr4bl3** [comment]
I understood you. I want to record continuously, but file was split by time.
Is it possible?

**Comment by Arkq** [comment]
No, it's not possible. The whole idea of VOR, is to trigger recording by signal level. Then, in order to save disk space and still know when the event has occurred, svar has output splitting (not interesting part of data, which is below signal level, will not be stored), so file creation time will tell the beginning of event.

**Comment by tr4bl3** [comment]
Thanks!
