### ISSUE TITLE
Help with usage...Devices, Sig-Level, and Duration

### ISSUE THREAD

**Issue by dtrikannad** [Arkq/svar#6]
Looking forward to getting this working. Thanks for making this. Here are my questions:

1. How do I find devices I can use? I have a couple USB cassette players and then also want to use line-in on the sound card. How do I know what the string should be to submit to -D?

2. how do i use the sig-level? Is that in DB?

3. is there a way to specify a duration I want it to run so it turns off automatically? How should I be closing the process?

Thanks

Deep

**Comment by Arkq** [comment]
> How do I know what the string should be to submit to -D?

With a standard build (without `-DENABLE_PORTAUDIO=ON`), `svar` uses ALSA as a back-end, so in order to get all capture devices use `arecord -L`. Otherwise, there will be an option for listing available PortAudio devices - `-L` or `--list-devices`.

> how do i use the sig-level? Is that in DB?

Sig-level is a value calculated by svar (it is not in dB). Use 'svar -m' to see signal level values in live. I think that you are right that maybe this sig-level option should be in `dB`... but that will require some work on this project...

> is there a way to specify a duration I want it to run so it turns off automatically? How should I be closing the process?

No there is no such option. In order to close process press 'Ctrl-C` (send interrupt signal).

**Comment by dtrikannad** [comment]
Thank you for your quick response. On the Device question, what would be
the string given the following response from arecord -l?

dtrikannad@deeps-ubuntu-server:~$ arecord -l
**** List of CAPTURE Hardware Devices ****
card 0: PCH [HDA Intel PCH], device 0: ALC889 Analog [ALC889 Analog]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: PCH [HDA Intel PCH], device 2: ALC889 Alt Analog [ALC889 Alt Analog]
  Subdevices: 2/2
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
card 1: Device [USB PnP Audio Device], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 2: Device_1 [USB PnP Audio Device], device 0: USB Audio [USB Audio]
  Subdevices: 0/1
  Subdevice #0: subdevice #0

**Comment by dtrikannad** [comment]
Sorry, should clarify...need to be able to record from the USB PnP Audio
Devices simultaneously. How do I identify each one distinctly...when it
comes to FFMPEG, I can select card # followed by Device ID...."hw:1,0" for
example...thats what i'm looking for on svar.

Thank you.
Deep

**Comment by Arkq** [comment]
`svar -D <name>` accepts the same name as `arecord -D <name>` accepts. It is a name of a capture PCM, e.g.: `svar -D hw:0,1` (if `arecord -D hw:0,1` works as well). On my PC there is no subdevice for microphone, so I can use only `svar -D hw:0`.
